name: icon_env
channels:
  - conda-forge
  - pytorch
  - pytorch3d
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.5.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - blas=2.120
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - cmake=4.2.3
  - colorama=0.4.6
  - cudatoolkit=10.2.89
  - cython=3.0.11
  - dataclasses=0.8
  - dav1d=1.2.1
  - eigen=3.4.0
  - embree=2.17.7
  - ffmpeg=6.0.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.16
  - fsspec=2024.10.0
  - fvcore=0.1.5.post20221221
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - geos=3.12.2
  - git=2.49.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.14
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - h2=4.1.0
  - harfbuzz=7.3.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.10
  - iopath=0.1.10
  - ittapi=3.25.2
  - jinja2=3.1.4
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20240116.2
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.18.0
  - libdeflate=1.17
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libspatialindex=2.0.0
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.21.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.18.0
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.5
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - make=4.4.1
  - markupsafe=2.1.5
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.1
  - ninja=1.13.2
  - numpy=1.24.4
  - openblas=0.3.30
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.6.1
  - p11-kit=0.24.1
  - pcre2=10.45
  - perl=5.32.1
  - pillow=9.4.0
  - pip=24.3.1
  - pixman=0.46.4
  - pkg-config=0.29.2
  - portalocker=2.10.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyembree=0.1.6
  - pysocks=1.7.1
  - python=3.8.19
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.4
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.3
  - rhash=1.4.6
  - rtree=1.3.0
  - setuptools=75.3.0
  - shapely=2.0.6
  - sleef=3.9.0
  - svt-av1=1.6.0
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.7.0
  - termcolor=2.4.0
  - tk=8.6.13
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025c
  - urllib3=2.2.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
    - Deprecated==1.3.1
    - Markdown==3.7
    - PyMCubes==0.1.2
    - PyMatting==1.1.14
    - PyWavelets==1.4.1
    - Werkzeug==3.0.6
    - absl-py==2.3.1
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==25.3.0
    - chumpy==0.70
    - click==8.1.8
    - cmake==4.2.1
    - coloredlogs==15.0.1
    - contourpy==1.1.1
    - cryptography==46.0.4
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - flatbuffers==25.12.19
    - flatten-dict==0.4.2
    - fonttools==4.57.0
    - frozenlist==1.5.0
    - future==1.0.0
    - google-auth==2.48.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.70.0
    - humanfriendly==10.0
    - imageio==2.35.1
    - importlib_metadata==8.5.0
    - importlib_resources==6.4.5
    - itsdangerous==2.2.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.7
    - kornia==0.7.3
    - kornia_rs==0.1.10
    - lazy_loader==0.4
    - lightning-utilities==0.11.9
    - llvmlite==0.41.1
    - loguru==0.7.3
    - marshmallow==3.22.0
    - matplotlib==3.7.5
    - multidict==6.1.0
    - mypy_extensions==1.1.0
    - ninja==1.13.0
    - numba==0.58.1
    - numpy==1.23.5
    - oauthlib==3.3.1
    - onnxruntime==1.16.3
    - opencv-python==4.13.0.90
    - opencv-python-headless==4.13.0.90
    - packaging==26.0
    - pip==25.0.1
    - pkgutil_resolve_name==1.3.10
    - platformdirs==4.3.6
    - pooch==1.8.2
    - propcache==0.2.0
    - protobuf==5.29.5
    - pyDeprecate==0.3.1
    - pyasn1==0.6.2
    - pyasn1_modules==0.4.2
    - pybind11==3.0.1
    - pyglet==1.5.31
    - pygltflib==1.16.5
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==1.5.10.post0
    - referencing==0.35.1
    - reindent==3.5.1
    - rembg==2.0.61
    - requests-oauthlib==2.0.0
    - rpds-py==0.20.1
    - rsa==4.9.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - setuptools==59.5.0
    - six==1.17.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tinyobjloader==2.0.0rc14.dev11+gd56555b
    - torchmetrics==1.5.2
    - trimesh==4.11.1
    - typing-inspect==0.9.0
    - typing_extensions==4.13.2
    - wrapt==2.0.1
    - yarl==1.15.2
    - zipp==3.20.2

prefix: "/mnt/sdb/CSC/fady/micromamba/envs/icon_env"
